use_frameworks!

platform :ios, '9.0'

target 'YEmptyDataView_Example' do
  pod 'YEmptyDataView', :path => '../'

  target 'YEmptyDataView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
